http:
  port: 8080
admin:
  port: 9876
  host: localhost
##################################################################################################
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  auth:
    paths: ['/auth/', '/auth/*']
  users:
    methods: 'GET,POST,PUT,PATCH,DELETE' 
    host: localhost
    paths: ['/users', '/users/*']
  account:
    host: localhost
    paths: ['/accounts', '/accounts/*']
  admin:
    host: localhost
    paths: '/admin/*'
<<<<<<< HEAD
  mail:
    host: localhost
    paths: '/email/*'
=======
>>>>>>> 399f36004a2e2b618529c15015b27faf5b05776e
    
##################################################################################################
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  usersService:
    url: 'http://localhost:8000'
  authService:
    url: 'http://localhost:8002'
  accountService:
    url: 'http://localhost:8004'
  adminService:
    url: 'http://localhost:8003'
<<<<<<< HEAD
  emailService:
    url: 'http://localhost:8005'
=======
>>>>>>> 399f36004a2e2b618529c15015b27faf5b05776e
##################################################################################################
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - oauth2
  - proxy
  - rate-limit
  - log
  - jwt
  - request-transformer
pipelines:
##################################################################################################
  usersPipeline:
<<<<<<< HEAD
    apiEndpoints:
      - users
    policies:
      - log:
        - action:
            message: "header===> ${req.header.authorization}"
      # - jwt:
      #   - action:
      #       secretOrPublicKey: 'mobaAuth'
      #       checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: usersService 
              changeOrigin: true

##################################################################################################
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - proxy:
        - action:
            serviceEndpoint: authService
            changeOrigin : true
##################################################################################################
  accountPipeline:
    apiEndpoints:
      - account
=======
    apiEndpoints:
      - users
>>>>>>> 399f36004a2e2b618529c15015b27faf5b05776e
    policies:
      - log:
        - action:
            message: "header===> ${req.header.authorization}"
      # - jwt:
      #   - action:
      #       secretOrPublicKey: 'mobaAuth'
      #       checkCredentialExistence: false
      - proxy:
          - action:
<<<<<<< HEAD
              serviceEndpoint: accountService 
=======
              serviceEndpoint: usersService 
>>>>>>> 399f36004a2e2b618529c15015b27faf5b05776e
              changeOrigin: true

##################################################################################################
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - proxy:
        - action:
            serviceEndpoint: authService
            changeOrigin : true
##################################################################################################
<<<<<<< HEAD
  adminPipeline:
    apiEndpoints:
      - admin
=======
  accountPipeline:
    apiEndpoints:
      - account
>>>>>>> 399f36004a2e2b618529c15015b27faf5b05776e
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
<<<<<<< HEAD
              serviceEndpoint: adminService 
              changeOrigin: true
##################################################################################################
adminPipeline:
    apiEndpoints:
      - email
=======
              serviceEndpoint: accountService 
              changeOrigin: true
##################################################################################################
  adminPipeline:
    apiEndpoints:
      - admin
>>>>>>> 399f36004a2e2b618529c15015b27faf5b05776e
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
<<<<<<< HEAD
              serviceEndpoint: emailService 
=======
              serviceEndpoint: adminService 
>>>>>>> 399f36004a2e2b618529c15015b27faf5b05776e
              changeOrigin: true
##################################################################################################
