http:
  port: 8080
admin:
  port: 9876
  host: localhost
##################################################################################################
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  test:
    host: localhost
    paths: '/test'
  users:
    host: localhost
    paths: ['/users', '/users/*']
  account:
    host: localhost
    paths: ['/accounts', '/accounts/*']
  admin:
    host: localhost
    paths: '/admin/*'
    
##################################################################################################
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  testing:
    url: 'http://localhost:3001'
  usersService:
    url: 'http://localhost:8000'
  accountService:
    url: 'http://localhost:8001'
  adminService:
    url: 'http://localhost:8003'
##################################################################################################
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
##################################################################################################
  ipPipeline:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
##################################################################################################
  testPipeline:
    apiEndpoints:
      - test
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: testing 
              changeOrigin: true
##################################################################################################
  usersPipeline:
    apiEndpoints:
      - users
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: usersService 
              changeOrigin: true
##################################################################################################
  accountPipeline:
    apiEndpoints:
      - account
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: accountService 
              changeOrigin: true
##################################################################################################
  adminPipeline:
    apiEndpoints:
      - admin
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: adminService 
              changeOrigin: true
##################################################################################################