http:
  port: 8080
admin:
  port: 9876
  host: localhost
##################################################################################################
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  auth:
    paths: ['/auth/', '/auth/*']
  users:
    methods: 'GET,POST,PUT,PATCH,DELETE' 
    host: localhost
    paths: ['/users', '/users/*']
  account:
    host: localhost
    paths: ['/accounts', '/accounts/*']
  admin:
    host: localhost
    paths: '/admin/*'
    
##################################################################################################
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  usersService:
    url: 'http://localhost:8000'
  authService:
    url: 'http://localhost:8002'
  accountService:
    url: 'http://localhost:8001'
  adminService:
    url: 'http://localhost:8003'
##################################################################################################
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - oauth2
  - proxy
  - rate-limit
  - log
  - jwt
  - request-transformer
pipelines:
##################################################################################################
  usersPipeline:
    apiEndpoints:
      - users
    policies:
      - log:
        - action:
            message: "header===> ${req.header.authorization}"
      # - jwt:
      #   - action:
      #       secretOrPublicKey: 'mobaAuth'
      #       checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: usersService 
              changeOrigin: true

##################################################################################################
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - proxy:
        - action:
            serviceEndpoint: authService
            changeOrigin : true
##################################################################################################
  accountPipeline:
    apiEndpoints:
      - account
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: accountService 
              changeOrigin: true
##################################################################################################
  adminPipeline:
    apiEndpoints:
      - admin
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: adminService 
              changeOrigin: true
##################################################################################################
