http:
  port: 8080
admin:
  port: 9876
  host: localhost
##################################################################################################
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  auth:
    host: localhost
    paths: ['/auth/', '/auth/*']
  users:
    methods: 'GET,POST,PUT,PATCH,DELETE' 
    host: localhost
    paths: ['/users/', '/users/*']
  
    
##################################################################################################
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  usersService:
    url: 'http://localhost:8000'
  authService:
    url: 'http://localhost:8001'
##################################################################################################
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - oauth2
  - proxy
  - rate-limit
  - log
  - jwt
  - request-transformer
pipelines:
##################################################################################################
  usersPipeline:
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: usersService 
              changeOrigin: true
##################################################################################################
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - log:
        - action:
            message: "header===> ${req.header.authorization}"
      - jwt:
        - action:
            secretOrPublicKey: 'mobaAuth'
            checkCredentialExistence: false
      - proxy:
        - action:
            serviceEndpoint: authService
            changeOrigin : true
#################################################################################################
